### PR TITLE
[WT-2645] Add necessary styles for dropdown dark mode

### PR DESCRIPTION
**Pull request by mmehmetAliIzci**

### CODE REVIEW

**Review by diego-antonelli — APPROVED** [review]

**Comment by diego-antonelli** [comment]
@mmehmetAliIzci target should be develop

**Review by diego-antonelli — CHANGES_REQUESTED** [review]
Target is wrong

**Review by diego-antonelli — DISMISSED** [review]

**Review by leonardomendix — APPROVED** [review]
Tested (iOS and Android) and it works as expected.

**Review by wegiswes — APPROVED** [review]

**Comment by wegiswes** [comment]
I've added the changes to Atlas 3 branch

**Pull request merged**
